### ISSUE TITLE
add dnsseed.nycoin.money seeder

### ISSUE THREAD

**Issue by ltanyc** [MrSlosh/NewYorkCoin-AuxPow#18]
We now have a dynmaic (auto-updating) seeder runnig for the NYCoin network at: dnsseed.nycoin.money

I've even took the time to secured it with DNSSEC so we should use it by default and perhas add more seeders as well.

If anyone wants to run a seeder our (Cloudflare enabled) seeder port is: https://github.com/ltanyc/nycoin-seeder

**Comment by nicovs** [comment]
have set up dnsseed.nycoin.community as well :)

**Comment by nicovs** [comment]
#21

**Comment by MrSlosh** [comment]
seeders merged. closing
