### ISSUE TITLE
datafolder

### ISSUE THREAD

**Issue by nicovs** [MrSlosh/NewYorkCoin-AuxPow#22]
in the new wallet, the datafolder is moved from 👍 
* Windows “C:\Users[USERNAME]\AppData\Roaming\newyorkc”.
* Mac  “~/Library/Application Support/newyorkc”
* Linux “~/.newyorkc”

to 
* Windows “C:\Users[USERNAME]\AppData\Roaming\NewYorkCoin”.
* Mac  “~/Library/Application Support/NewYorkCoin”
* Linux “~/.newyorkcoin

We should revert that probably, not to make the users to redownload the entire thing

**Comment by nicovs** [comment]
util.cpp

**Comment by MrSlosh** [comment]
Ok, done and pushed.
